[package]
name = "nonogram-bench"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[dependencies]
nonogram = { path = "../nonogram" }

[[bench]]
name = "main"
harness = false
